### ISSUE TITLE
Activation link do nothing

### ISSUE THREAD

**Issue by blondie63** [devaslanphp/help-desk#131]
**Describe the bug**
Added a new user, the system send activation email but the activation link do nothing..

**Comment by heloufir** [comment]
Hello @blondie63 

I will check it asap and give you more information.
Thanks for reporting the issue.

**Comment by blondie63** [comment]
I'm testing locally so i leave APP_URL=http://localhost
do you think a need to change it ?

**Comment by heloufir** [comment]
> I'm testing locally so i leave APP_URL=http://localhost do you think a need to change it ?

Yes you need to update this variable to your local url, if you use `php artisan serve` so need to put `http://localhost:8000` in this variable.

**Comment by blondie63** [comment]
i've modified app_url and now activation email arrive with a link like this:
http://localhost:8000/auth/activate-account/ce6f18af-22e8-41fe-97d5-e3cf3673f12f

But this link still not activate the account

**Comment by heloufir** [comment]
hmm okey, I will check and let you know ASAP.

**Comment by blondie63** [comment]
I've checked also previous activation email and have same link with :8000 also if app_url was only localhost

**Comment by heloufir** [comment]
I just checked the system in my local, and it works!
When you click the activation the link you got this page (see the below screenshot) you need to choose your password and confirm it then submit the form.

Important: If you click on the link in a browser where you are already logged in, you need to open the link on another browser to simulate the new user that wan't to activate his account.

![image](https://user-images.githubusercontent.com/6197875/197234002-6d464b8b-7116-40bb-8ad9-bc4faad76413.png)

**Comment by heloufir** [comment]
@blondie63 yes that's it.
I will close the issue, if needed you can reopen it.
