### ISSUE TITLE
Table icon

### ISSUE THREAD

**Issue by cristian-araujo** [devaslanphp/help-desk#79]
**Describe the bug**
Icon table migration is not in the repository and it is necessary for tickets types.

**To Reproduce**
Clone repository, configure database and run migrations

**Expected behavior**
Migration for icon table

**Screenshots**
![image](https://user-images.githubusercontent.com/72935660/192074311-cffd62a7-0358-400b-bf13-a5c53309b312.png)

**Comment by heloufir** [comment]
As described in the docs, the 5th step of installation, you need to execute the database seeder, in this step the icons table is created and filled with data:

´´´php

Database seed: using the docker terminal for laravel.test-1 container run this command php artisan db:seed

´´´

**Comment by cristian-araujo** [comment]
> As described in the docs, the 5th step of installation, you need to execute the database seeder, in this step the icons table is created and filled with data:
> 
> > 5. Database seed: using the docker terminal for laravel.test-1 container run this command
> 
> ```shell
> php artisan db:seed
> ```
> 
> https://laravel-help-desk.herokuapp.com/docs/#idocs_installation

thank you for the fast response.

I think a create table inside a migration is not the proper way

**Comment by heloufir** [comment]
Yes I totally agree with you, an improvement of the icons function is in progress, it will have a seeder for the schema and an update of seeder to have all the icons list of the latest fontawesome icons set.

**Comment by heloufir** [comment]
@cristian-araujo 
A PR was made to migrate the `icons` schema definition to a migration, and also the seeder of fontawesome icons list is updated to the last set (based on the metadata [https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/icons.json](https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/icons.json))

PR: #80

**Comment by cristian-araujo** [comment]
> @cristian-araujo A PR was made to migrate the `icons` schema definition to a migration, and also the seeder of fontawesome icons list is updated to the last set (based on the metadata https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/icons.json)
> 
> PR: #80

thank you, I think this help desk has much potential, but in real scenario it need to be improved a little more.

I have some ideas for it, I was thinking to fork this project and make the changes by myself but if you want, I can share the improvements.

sorry for my english, i'm still learning it

**Comment by heloufir** [comment]
Any contribution (idea, code, …) helping to improve this application will be welcome.
You can use the conversation section of this repository to share ideas, or make pull request as you like.

Thank you in advance.
